spring:
  application:
    name: WeatherTurkey
  # Veritaban? Ayarlar?
  datasource:
    url: jdbc:postgresql://localhost:5434/weatherdb
    driver-class-name: org.postgresql.Driver
    username: burak
    password: 12345
  # JPA/Hibernate Ayarlar?
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# OpenWeatherMap API Ayarlar?
openweathermap:
  api:
    key: ${OPENWEATHER_API_KEY:}
    url: https://api.openweathermap.org/data/2.5/weather

# JWT (JSON Web Token) Ayarlar?
jwt:
  secret: "BuCokGizliBirAnahtarOlmalidirVeUretilmesiGerekenGuvenliBirDegerdir1234567890"
  expiration:
    ms: 1800000 # 30 Dakika

# Loglama Seviyeleri
logging:
  level:
    org:
      springframework:
        security: DEBUG